### ISSUE TITLE
mysql_connect() not connecting

### ISSUE THREAD

**Issue by alvapatrice** [kangchuang/shop#1]
mysql_connect()  不支持.  怎么操作？

**Comment by kangchuang** [comment]
config文件夹datebase.php文件是配置连接数据库的

**Comment by kangchuang** [comment]
你现在用他干嘛，我都还没开始开发，就是一个空框架

**Comment by alvapatrice** [comment]
发错了，应该是要发到另外个项目。sorry。 you can close this issue

P Nostalgie
Chengdu Neusoft University
________________________________

**Comment by kangchuang** [comment]
。。。。
